version: '3.9'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: dreamzito
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  # api:
  #   build: .
  #   ports:
  #     - 3001:3001
  #   environment:
  #     DATABASE_URL: postgresql://root:root@localhost:5432/dreamzito?schema=public
  #     JWT_SECRET: "teste"
